### ISSUE TITLE
Swarm usage

### ISSUE THREAD

**Issue by w0rldart** [omallo/docker-volume-plugin-dostorage#11]
Hello there! Hopefully you can shed some light into my confusion on how to integrate this with Swarm configuration.

The scenario is one where I have 1 manager and 3 workers.

 * _"The Docker volume must be created on every Docker host separately (using docker volume create as described above)."_

Do you mean I have to create the volume on all 4 hosts in order for it to be working?

 * _"A DigitalOcean volume can only be attached to a single droplet at the same time. For that reason, you must not run Docker containers concurrently on different hosts which use the same DigitalOcean volume."_

How will that cope with replicated droplets?

**Comment by omallo** [comment]
Hi @w0rldart 

Here is my feedback to your questions:
- Yes, you have to create the volume on every node separately. This is because the driver is defined to have scope `local` as described [here](https://docs.docker.com/engine/extend/plugins_volume/#/volumedrivercapabilities). Docker also supports a `global` scope but I would have to investigate how global scopes work since the documentation does not say too much about it. I've created an issue #12 to investigate this.
- Unfortunately, the limitation of only being able to attach a volume to a single droplet is a technical limitation of DigitalOcean itself. Being able to attach a volume to multiple droplets is a commonly requested feature. You can find a discussion about this topic [here](https://www.digitalocean.com/community/tutorials/how-to-use-block-storage-on-digitalocean?comment=49111). This means that if you have multiple containers accessing the same volume, they must all run on the same droplet.

**Comment by w0rldart** [comment]
Fantastic explanation  @omallo! Thank you, as you saved me a whole lot of time having to look through all of that, that I don't have any experience with. Feel free to close the issue

**Comment by omallo** [comment]
You're welcome :-)
