### ISSUE TITLE
Question about mount process

### ISSUE THREAD

**Issue by uLan08** [omallo/docker-volume-plugin-dostorage#14]
I have everything set up and it's all working fine. I just have a question about the whole mounting process. 
Before I created a volume, I typed in these commands to format and partition the volume.
```
sudo parted /dev/disk/by-id/scsi-0DO_Volume_volume-nyc1-01 mklabel gpt
sudo parted -a opt /dev/disk/by-id/scsi-0DO_Volume_volume-nyc1-01 mkpart primary ext4 0% 100%
sudo mkfs.ext4 /dev/disk/by-id/scsi-0DO_Volume_volume-nyc1-01-part1
sudo mkdir -p /mnt/volume-nyc1-01-part1
echo '/dev/disk/by-id/scsi-0DO_Volume_volume-nyc1-01-part1 /mnt/volume-nyc1-01-part1 ext4 defaults,nofail,discard 0 2' | sudo tee -a /etc/fstab
sudo mount -a
```
 https://www.digitalocean.com/community/tutorials/how-to-use-block-storage-on-digitalocean#preparing-volumes-for-use-in-linux

Then I created the volume configured with the driver, when I type in ` ls -l /mnt/ ` I now see two mount points there. First is the one the driver created and the other is the one I created by running those commands. Files are appearing as they should, in ` /mnt/dostarage/volume-name`. Now the question is what is the other mount point I created for? Was it just for testing purposes? If so, should I just disregard and unmount it? How come ` /mnt/dostorage/volume-name ` is not listed in `/etc/fstab` ? It is also not listed when running ` findmnt ` command

This whole process is totally new for me, so please enlighten me.

**Comment by omallo** [comment]
The second mount point you created as well as the entry in the `/etc/fstab` file are both not needed by the driver. This is because the driver mounts and unmounts the block storage device automatically when needed. What the driver does is essentially the following:
- When the block storage is referenced for the first time by a container on a droplet, the driver calls `mount <device> <mountpoint>` on that droplet.
- When the last reference of a container to the block storage is removed on a droplet, the driver calls `umount <mountpoint>` on that droplet.

The reason why the block storage device is unmounted once the last reference to it was removed is that the device might then be used on a different droplet (block storage devices can only be attached to a single droplet at a time). So, in general, you should not mount the block storage device manually unless you really need to.

**Comment by uLan08** [comment]
Ah, that makes sense. So should I just unmount the other mount point that I created? Would not unmounting it cause any issues with the driver? Also, I encountered a problem last time. But I am not able to reproduce it. When I tried to run my docker containers, it displayed an error about not detecting the volume I created. I ` docker volume ls ` and it was not listed there.  So I tried creating again the volume but it was complaining something about the driver not being found. I typed in ` docker-volume-plugin-dostorage --version ` and it is installed. I thought that somehow it was not running in the background, so I typed in ` docker-volume-plugin-dostorage --access-token=<your-API-Access-Token> & ` and ` docker volume ls ` and it was listed there then I was able to run my containers again. What's weird is that I was able to successfully run my containers before.

**Comment by omallo** [comment]
You can just unmount the directory you mounted manually. This has no effect on the mount done by the driver.

Regarding the error of the driver not being found, it is likely to be because of the driver not being running in the background but if you encounter the problem again, you might want to create an issue if you think it's a different problem.

**Comment by uLan08** [comment]
Oh okay, thanks for the help! I look forward to more features from this driver,
